name: 'Cypress Check'
description: 'Add checks after cypress run'
author: 'bley'
branding:
  icon: 'check-circle'
  color: 'green'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  token:
    description: 'GITHUB_TOKEN'
    required: true
  cypress_folder:
    description: 'contains reports & other output'
    required: true
  s3_url:
    description: 'S3 url for videos'
    required: true