name: 'Cypress Check'
description: 'Add checks after cypress run'
author: 'bley'

inputs:
  GITHUB_TOKEN: 
    description: 'GitHub Token'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
